baseURL = 'https://tyotalks.org/'
languageCode = 'en-us'
title = 'Tyo Talks'
theme = 'diary'
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    url = "/posts"
    name = "Posts"
    weight = 1

[[menu.main]]
    url = "/documents"
    name = "Documents"
    weight = 2

[[menu.main]]
    url = "/drafts"
    name = "Drafts"
    weight = 3

[[menu.main]]
    url = "/notes"
    name = "Notes"
    weight = 4